# Generated by Django 4.0.3 on 2022-03-15 05:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('recipe_steps', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=20)),
                ('preparation_time', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('times_added', models.IntegerField()),
                ('is_created', models.BooleanField()),
                ('creation_date', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NutricionalValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fats', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('votes', models.IntegerField()),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='api.menucategory')),
                ('dishes', models.ManyToManyField(to='api.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('categories', models.ManyToManyField(to='api.ingredientcategory')),
                ('nutricional_value', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.nutricionalvalue')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(to='api.dishcategory'),
        ),
        migrations.AddField(
            model_name='dish',
            name='original_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_original', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='utensils',
            field=models.ManyToManyField(to='api.utensil'),
        ),
    ]
