# Generated by Django 3.2.8 on 2022-03-12 15:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('recipe_steps', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=20)),
                ('preparation_time', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('times_added', models.IntegerField()),
                ('is_created', models.BooleanField()),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NutricionalValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fats', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('votes', models.IntegerField()),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('categories', models.ManyToManyField(to='api.MenuCategory')),
                ('dish_list', models.ManyToManyField(to='api.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('categories', models.ManyToManyField(to='api.IngredientCategory')),
                ('nutricional_value', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.nutricionalvalue')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_author', to='api.user'),
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(to='api.DishCategory'),
        ),
        migrations.AddField(
            model_name='dish',
            name='original_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_original', to='api.user'),
        ),
        migrations.AddField(
            model_name='dish',
            name='utensils',
            field=models.ManyToManyField(to='api.Utensil'),
        ),
    ]
