# Generated by Django 3.2.8 on 2022-03-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dish_list',
            new_name='dishes',
        ),
    ]
