# Generated by Django 4.0.3 on 2022-03-15 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dish_name_alter_dish_original_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe_steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=100),
        ),
    ]
