# Generated by Django 3.2.8 on 2022-03-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dish_is_published_alter_dish_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='icon',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='name',
            field=models.CharField(default='dishcat', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='icon',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(default='ingrecat', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='icon',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name',
            field=models.CharField(default='menucat', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utensil',
            name='icon',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='utensil',
            name='name',
            field=models.CharField(default='utensil', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
