# Generated by Django 3.2.8 on 2022-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220316_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='api.Ingredient'),
        ),
    ]
