# Generated by Django 4.0.3 on 2022-03-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dish_categories_alter_dish_recipe_steps_and_more'),
        ('api', '0005_dish_ingredients'),
    ]

    operations = [
    ]
