# Generated by Django 4.0.3 on 2022-03-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20220317_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='original_author',
            new_name='original_author_id',
        ),
    ]
