# Generated by Django 3.2.8 on 2022-03-17 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_rename_author_dish_author_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='author',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dishes',
        ),
        migrations.AddField(
            model_name='menu',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_ids',
            field=models.ManyToManyField(to='api.Dish'),
        ),
    ]
