# Generated by Django 4.0.3 on 2022-03-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220317_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dish_ids',
            new_name='dish_list',
        ),
    ]
